name: Build MyTweak

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      THEOS: ${{ github.workspace }}/theos
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2.0'

    - name: Setup Theos
      uses: actions/checkout@v4
      with:
         repository: theos/theos
         path: ${{ github.workspace }}/theos
         submodules: recursive

    - name: Install Dependencies
      run: |
        brew install make dpkg ldid
        echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

    - name: Build Tweak (release)
      run: |
        make package FINALPACKAGE=1
        echo "filename=$(find . -name '*debug*' -path './packages/*' | cut -d/ -f3)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4
      with:
        name: ${{env.filename}}
        path: packages/${{env.filename}}
        if-no-files-found: error

    - name: Build Tweak (rootful)
      run: |
        make package FINALPACKAGE=1
        echo "filename=$(find . -not -name '*debug*' -path './packages/*' | cut -d/ -f3)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4
      with:
        name: ${{env.filename}}
        path: packages/${{env.filename}}
        if-no-files-found: error

    - name: Build Tweak (rootless)
      run: |
        make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
        echo "filename=$(find . -name '*arm64*' -path './packages/*' | cut -d/ -f3)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4
      with:
        name: ${{env.filename}}
        path: packages/${{env.filename}}
        if-no-files-found: error
